version: '3.1'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongodb
